version: '3.8'

services:
  postgres:
    image: postgres
    container_name: shop
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shop
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: celery -A celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://localhost:6379
    network_mode: "host"

volumes:
  postgres_data:
