version: '3.7'
services:
  postgres:
    image: postgres
    container_name: shop
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shop
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
