# Generated by Django 5.0.7 on 2024-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Product categories"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена"),
        ),
    ]
