# Generated by Django 5.0.7 on 2024-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbalance",
            name="balance",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name="Баланс юзера"),
        ),
    ]
