# Generated by Django 5.0.7 on 2024-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_productcategory_options_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="old_price",
        ),
        migrations.AlterField(
            model_name="product",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Остаток товара на складе"),
        ),
    ]
