# Generated by Django 5.0.7 on 2024-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_price_product_old_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Процент скидки"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена без скидки"
            ),
        ),
    ]
