# Generated by Django 5.0.7 on 2024-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_discount_alter_product_old_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
    ]
