# Generated by Django 5.0.7 on 2024-08-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
