# Generated by Django 5.0.7 on 2024-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_product_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступность товара"),
        ),
        migrations.AddField(
            model_name="product",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Остаток товара на складе"),
        ),
    ]
