# Generated by Django 5.0.7 on 2024-08-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Корзина"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Категории товаров"},
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена со скидкой"),
            preserve_default=False,
        ),
    ]
