# Generated by Django 5.0.7 on 2024-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_cart_product_remove_cart_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name="Цена со скидкой"),
        ),
    ]
