# Generated by Django 5.0.7 on 2024-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name="Цена со скидкой"),
        ),
    ]
