# Generated by Django 5.0.7 on 2024-08-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
