# Generated by Django 5.0.7 on 2024-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена со скидкой"
            ),
        ),
    ]
